---
features:
  - |
    Bumped Horizon kolla image
    Bumped Grafana from 10.1.5-1 to 10.4.2-1 (Rocky Linux)
    Bumped Grafana from 10.4.1 to 10.4.2 (Ubuntu)
    Bumped Prometheus-msteams from 1.5.1 to 1.5.2
security:
  - |
    Fixed CVE-2023-31047 for Horizon.
    Fixed CVE-2023-49569 for Grafana.
    Fixed CVE-2022-40083 and CVE-2021-4238 for Prometheus-msteams.
