# yamllint disable-file
---
# Use prebuilt release train images from Ark.
{% if stackhpc_download_overcloud_host_images | bool %}
use_cirros: true
cirros_deploy_image_upstream_url: "{{ stackhpc_overcloud_host_image_url }}"
{% endif %}
