---
- name: ADVise run
  hosts: localhost
  gather_facts: no
  tags:
    - advise
  vars:
    venv: "~/venvs/advise-review"
    input_dir: "{{ lookup('env', 'PWD') }}/overcloud-introspection-data"
    output_dir: "{{ lookup('env', 'PWD') }}/review"
    advise_pattern: ".*.eval"  # Uses regex
  tasks:
    - name: Install dependencies
      pip:
        virtualenv: "{{ venv }}"
        virtualenv_command: "/usr/bin/python3 -m venv"
        name:
          - git+https://github.com/stackhpc/ADVise
        state: latest

    - name: Create data directory
      file:
        path: '{{ output_dir }}/data'
        state: directory

    - name: Extract data
      shell:
        cmd: >
          {{ venv }}/bin/m2-extract {{ input_dir }}/*.json --output_dir {{ output_dir }}/data

    - name: Create review directory
      file:
        path: '{{ output_dir }}/results'
        state: directory

    - name: Process data
      shell:
        cmd: >
          {{ venv }}/bin/advise-process
          -I ipmi
          -p '{{ output_dir }}/data/extra-hardware/{{ advise_pattern }}'
          -o '{{ output_dir }}'

    - name: Visualise data
      command: >
        {{ venv }}/bin/advise-visualise
        --output_dir '{{ output_dir }}'
