---
- name: Ensure additional Ceph commands are run
  gather_facts: false
  hosts: mons
  become: true
  tags:
    - cephadm
    - cephadm-commands
  tasks:
    - import_role:
        name: stackhpc.cephadm.commands