---
- name: Configure VXLAN
  hosts: controllers,compute,seed,storage
  gather_facts: true
  vars:
    ansible_user: "{{ bootstrap_user }}"
    # We can't assume that a virtualenv exists at this point, so use the system
    # python interpreter.
    ansible_python_interpreter: /usr/bin/python3
    # Work around no known_hosts entry on first boot.
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  roles:
    - role: stackhpc.vxlan
