---
- name: Configure VXLAN
  hosts: storage,seed,controllers,compute
  gather_facts: false
  vars:
    ansible_user: "{{ bootstrap_user }}"
    # We can't assume that a virtualenv exists at this point, so use the system
    # python interpreter.
    ansible_python_interpreter: /usr/bin/python3
    # Work around no known_hosts entry on first boot.
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  roles:
    - role: vxlan
      vars:
        vxlan_phys_dev: "{{ admin_oc_net_name | net_interface }}"
        vxlan_dstport: 4790
        vxlan_interfaces:
          - device: vxlan10
            group: 224.0.0.10
            bridge: breth1
