---
# Currently the pulp_deb plugin in Pulp does not support certain types of
# content, including i18n files and command-not-found indices. This breaks APT
# when the command-not-found is installed. This playbook can be used to
# uninstall the package, prior to running any other APT commands. It may be
# installed as a hook to the 'host configure' commands.
# See https://github.com/pulp/pulp_deb/issues/419
# FIXME: If used as a hook, this playbook matches all hosts, so will run
# against the seed, even when running 'overcloud host configure'. Depending on
# the stage of deployment, some hosts may be unreachable. This could be fixed
# by implementing this playbook separately for each group.
- name: Purge command-not-found package
  hosts: seed-hypervisor:seed:overcloud:infra-vms
  gather_facts: false
  vars:
    ansible_user: "{{ bootstrap_user }}"
    # We can't assume that a virtualenv exists at this point, so use the system
    # python interpreter.
    ansible_python_interpreter: /usr/bin/python3
    # Work around no known_hosts entry on first boot.
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Purge command-not-found package
      package:
        name:
          - command-not-found
          - python3-command-not-found
        purge: true
        state: absent
      become: true
      failed_when: false
      ignore_unreachable: true
      when: os_distribution == "ubuntu"
