---
collections:
  - name: stackhpc.cephadm
    version: 1.13.2
  - name: stackhpc.pulp
    version: 0.4.1
  - name: stackhpc.hashicorp
    version: 2.4.0
roles:
  - src: stackhpc.vxlan
  - name: ansible-lockdown.rhel8_cis
    src: https://github.com/ansible-lockdown/RHEL8-CIS
    version: 1.3.0
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc
