---
collections:
  - name: stackhpc.cephadm
    version: 1.14.0
  # NOTE: Pinning pulp.squeezer to 0.0.13 because 0.0.14+ depends on the
  # pulp_glue Python library being installed.
  - name: pulp.squeezer
    version: 0.0.13
  - name: stackhpc.pulp
    version: 0.5.2
  - name: stackhpc.hashicorp
    version: 2.4.0
roles:
  - src: stackhpc.vxlan
  - name: ansible-lockdown.rhel9_cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: v1.0.0
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc
