---
collections:
  - name: stackhpc.cephadm
    version: 1.18.0
  # NOTE: Pinning pulp.squeezer to 0.0.13 because 0.0.14+ depends on the
  # pulp_glue Python library being installed.
  - name: pulp.squeezer
    version: 0.0.13
  - name: stackhpc.pulp
    version: 0.5.5
  - name: stackhpc.hashicorp
    version: 2.5.1
  - name: stackhpc.kayobe_workflows
    version: 1.0.3
roles:
  - src: stackhpc.vxlan
  - name: ansible-lockdown.ubuntu22_cis
    version: 1.4.0
  - name: ansible-lockdown.rhel9_cis
    version: 1.3.1
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc
  - name: geerlingguy.pip
    version: 2.2.0
  - name: monolithprojects.github_actions_runner
    version: 1.18.5
  - src: https://github.com/stackhpc/ansible-role-docker.git
    name: geerlingguy.docker
