---
collections:
  - name: stackhpc.cephadm
    version: 1.14.0
  # NOTE: Pinning pulp.squeezer to 0.0.13 because 0.0.14+ depends on the
  # pulp_glue Python library being installed.
  - name: pulp.squeezer
    version: 0.0.13
  - name: stackhpc.pulp
    version: 0.4.1
  - name: stackhpc.hashicorp
    version: 2.4.0
  - name: stackhpc.kayobe_workflows
    version: 1.0.2
roles:
  - src: stackhpc.vxlan
  - name: ansible-lockdown.rhel8_cis
    src: https://github.com/ansible-lockdown/RHEL8-CIS
    version: 1.3.0
  - name: ansible-lockdown.ubuntu22_cis
    src: https://github.com/ansible-lockdown//UBUNTU22-CIS
    #FIXME: Waiting for https://github.com/ansible-lockdown/UBUNTU22-CIS/pull/132
    # to be in a tagged release
    version: c91a1038fd218f727075d21b2d0880751322b162
  - name: ansible-lockdown.rhel9_cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    #FIXME: Waiting for https://github.com/ansible-lockdown/RHEL9-CIS/pull/54
    # to be in a tagged release.
    version: 3525cb6aab12a3d1e34aa8432ed77dd76be6a44a
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc
  - name: geerlingguy.pip
    version: 2.2.0
  - name: monolithprojects.github_actions_runner
    version: 1.18.5
  - src: https://github.com/stackhpc/ansible-role-docker.git
    name: geerlingguy.docker
