---
collections:
  - name: stackhpc.pulp
    version: 0.3.0
  - name: pulp.squeezer
    version: 0.0.11
roles:
  - name: vxlan
    src: https://github.com/stackhpc/ansible-role-vxlan.git
    version: b506e9817e1eb0a81ea66e0cddc40ab2ff66bc79
