---
collections:
  - name: stackhpc.cephadm
    version: 1.12.2
  - name: stackhpc.pulp
    version: 0.4.1
roles:
  - src: stackhpc.vxlan
  - name: ansible-lockdown.rhel8_cis
    src: https://github.com/ansible-lockdown/RHEL8-CIS
    version: 1.3.0
