{% if stackhpc_enable_os_capacity | bool %}
{% raw %}
scrape_configs:
  - job_name: os-capacity
    static_configs:
        - targets:
          - '{{ kolla_internal_vip_address | put_address_in_context('url') }}:9000'
    scrape_interval: 15m
    scrape_timeout: 10m
{% endraw %}
{% endif %}
