---
# Kayobe time configuration.

###############################################################################
# Network Time Protocol (NTP).

# List of NTP time sources to configure. Format is a list of dictionaries with
# the following keys:
# server:  host or pool
# type:    (Optional) Defaults to server. Maps to a time source in the
#           configuration file. Can be one of server, peer, pool.
# options: (Optional) List of options that depends on type, see Chrony
#          documentation for details.
# See: https://chrony.tuxfamily.org/doc/4.0/chrony.conf.html
#
# Example of configuring a pool and customising the pool specific maxsources
# option:
# chrony_ntp_servers:
#   - server: pool.ntp.org
#     type: pool
#     options:
#       - option: maxsources
#         val: 3
#
chrony_ntp_servers:
  - server: "{{ provision_oc_net_name | net_ip(inventory_hostname=groups['seed'][0]) }}"
