---
name: Pull request
'on':
  pull_request:
jobs:
  tox:
      runs-on: ubuntu-20.04
      strategy:
        matrix:
          include:
            - environment: pep8
              python-version: 3.8
            - environment: releasenotes
              python-version: 3.8
      name: Tox ${{ matrix.environment }} with Python ${{ matrix.python-version }}
      steps:
        - name: Github Checkout ğŸ›u
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Setup Python ${{ matrix.python-version }} ğŸ
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Tox ğŸ“¦
          run: pip install tox 
        - name: Run Tox ${{ matrix.environment }} ğŸ§ª
          run: tox -e ${{ matrix.environment }} 
