---

concurrency:
  group: stackhpc-pull-request-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Pull request
'on':
  pull_request:
jobs:
  tox:
    runs-on: ubuntu-22.04
    permissions: {}
    strategy:
      matrix:
        include:
          - environment: pep8
            python-version: "3.10"
          - environment: releasenotes
            python-version: "3.10"
          - environment: docs
            python-version: "3.10"
    name: Tox ${{ matrix.environment }} with Python ${{ matrix.python-version }}
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
    steps:
      - name: GitHub Checkout üõé
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python ${{ matrix.python-version }} üêç
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox üì¶
        run: pip install tox
      - name: Run Tox ${{ matrix.environment }} üß™
        run: tox -e ${{ matrix.environment }}

  build-kayobe-image:
    name: Build Kayobe Image
    uses: ./.github/workflows/stackhpc-build-kayobe-image.yml
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'

  all-in-one-ubuntu-jammy-ovs:
    name: aio (Ubuntu Jammy OVS)
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-all-in-one.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: ubuntu
      os_release: jammy
      ssh_username: ubuntu
      neutron_plugin: ovs
      OS_CLOUD: sms-lab-release
    secrets: inherit
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'

  all-in-one-ubuntu-jammy-ovn:
    name: aio (Ubuntu Jammy OVN)
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-all-in-one.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: ubuntu
      os_release: jammy
      ssh_username: ubuntu
      neutron_plugin: ovn
      OS_CLOUD: sms-lab-release
    secrets: inherit
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'

  all-in-one-rocky-9-ovs:
    name: aio (Rocky 9 OVS)
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-all-in-one.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: rocky
      os_release: "9"
      ssh_username: cloud-user
      neutron_plugin: ovs
      OS_CLOUD: sms-lab-release
    secrets: inherit
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'

  all-in-one-rocky-9-ovn:
    name: aio (Rocky 9 OVN)
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-all-in-one.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: rocky
      os_release: "9"
      ssh_username: cloud-user
      neutron_plugin: ovn
      OS_CLOUD: sms-lab-release
    secrets: inherit
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
