---
name: Promote Pulp repositories
on:
  push:
    branches:
      # NOTE(upgrade): Reference only the current release branch here.
      - stackhpc/zed
jobs:
  promote:
    name: Trigger Pulp promotion workflows
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      # NOTE(mgoddard): Trigger another CI workflow in the
      # stackhpc-release-train repository.
      - name: Trigger package repository promotion
        run: |
          gh workflow run \
          package-promote.yml \
          --repo stackhpc/stackhpc-release-train \
          --ref main \
          -f kayobe_config_branch=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.STACKHPC_RELEASE_TRAIN_TOKEN }}

      - name: Display link to package repository promotion workflows
        run: |
          echo "::notice Package repository promote workflow: https://github.com/stackhpc/stackhpc-release-train/actions/workflows/package-promote.yml"

      # NOTE(mgoddard): Trigger another CI workflow in the
      # stackhpc-release-train repository.
      - name: Trigger container image promotion
        run: |
          gh workflow run \
          container-promote.yml \
          --repo stackhpc/stackhpc-release-train \
          --ref main \
          -f kayobe_config_branch=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.STACKHPC_RELEASE_TRAIN_TOKEN }}

      - name: Display link to container image promotion workflows
        run: |
          echo "::notice Container image promote workflow: https://github.com/stackhpc/stackhpc-release-train/actions/workflows/container-promote.yml"
