---
name: Tag & Release
'on':
  push:
    branches:
      - stackhpc/yoga
permissions:
  contents: write
jobs:
  tag-and-release:
    uses: stackhpc/.github/.github/workflows/tag-and-release.yml@main
    with:
      upstream: https://github.com/openstack/kayobe-config
